### ISSUE TITLE
About raw signals

### ISSUE THREAD

**Issue by Edwardyao1997** [berkanlafci/oadat#4]
I download the SWFD_ss_rawBP-mini.h5 file from the dataset. But the raw signal is not optoacoustic signal at all when I opened them in MATLAB. The images can't be reconstructed from provided signals. May I get a guideline about how to use the correct data?

**Comment by firatozdemir** [comment]
I am not entirely sure if I understand your question, but following your request, I just extended a demo notebook to also cover raw signal data. 
Please have a look at [demo_raw_and_BP.ipynb](https://renkulab.io/gitlab/firat.ozdemir/oadat-explore/-/blob/master/notebooks/demo_raw_and_BP.ipynb) at [oadat-explore repo](https://renkulab.io/projects/firat.ozdemir/oadat-explore).

**Comment by firatozdemir** [comment]
Closing as issue has gone stale.
